language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
sudo: false
script: ./.travis.sh 

env:
  - SSL_FLAG="--without-ssl" LUA_FLAG="--without-liblua"
  - SSL_FLAG="" LUA_FLAG="--without-liblua"
  - SSL_FLAG="--without-ssl" LUA_FLAG=""
  - SSL_FLAG="" LUA_FLAG=""

notifications:
  irc:
    channels:
      - "chat.freenode.net#nmap"
    on_success: change
    on_failure: always
